### ISSUE TITLE
Parsing Problems

### ISSUE THREAD

**Issue by nwoodthorpe** [NATHAN4/WatWhenWhere#1]
Parsing has a distaste for thursdays and doesn't include labs.

**Comment by sarthfrey** [comment]
i cri erytim

**Comment by nwoodthorpe** [comment]
Fam stuff, illl do it v soon

**Comment by nwoodthorpe** [comment]
LAB issue fixed, can't reproduce thursday issue.

**Comment by sarthfrey** [comment]
yo we need to account for SEM as well

**Comment by nwoodthorpe** [comment]
Fuck

**Comment by nwoodthorpe** [comment]
Le fixed

**Comment by sarthfrey** [comment]
ayy lmao
