### ISSUE TITLE
Friend Search is sketch

### ISSUE THREAD

**Issue by Lixire** [NATHAN4/WatWhenWhere#21]
![image](https://cloud.githubusercontent.com/assets/13241824/12073285/f4c33f22-b0e4-11e5-9dd5-e0e5c0032653.png)
![12483386_1068291896524251_1966213498_n](https://cloud.githubusercontent.com/assets/13241824/12073287/0c4fa9f0-b0e5-11e5-94a7-2cf1af78f351.jpg)

they come from the same query :'D

**Comment by tiffanynwyeung** [comment]
from the words of Nate: they grab the first ten results that closely match the input string (cuz i was complaining about that too)

**Comment by nwoodthorpe** [comment]
Fixing now

**Comment by nwoodthorpe** [comment]
Fixed, the tolerance might need adjusting but it seems better.
