### ISSUE TITLE
On Mobile site: back button is way to big on compare.html

### ISSUE THREAD

**Issue by S-Kantor** [NATHAN4/WatWhenWhere#23]
![whatwho](https://cloud.githubusercontent.com/assets/5102847/12073295/7bb97ba4-b0e5-11e5-8cae-1be83595b405.png)

**Comment by edwardhdlu** [comment]
Omg.

Is this only on compare.html?

**Comment by S-Kantor** [comment]
Yup

**Comment by edwardhdlu** [comment]
Fixed, thanks!
