### ISSUE TITLE
Co-op schedule doesn't load anything

### ISSUE THREAD

**Issue by AroundTheLines** [NATHAN4/WatWhenWhere#25]
Sample input:

```
GO!

Qi Wang


My Academics

Course Selection (Undergrad only)

Enroll

GO Pass




my class schedule

add

drop

swap

component swap

appointments

search for classes


My Class Schedule
List View
Weekly Calendar View
Select Display Option
Winter 2016 | Undergraduate | University of Waterloo
COOP 1 - Co-operative Work Term
Status  Units   Grading Grade
Enrolled
0.50
Credit/No Credit Co-op

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
7433
002
WRK
TBA
TBA
Staff
01/04/2016 - 04/04/2016
Exam Information

PD 20 - Eng'g Workplce Skills I:
Status  Units   Grading Grade
Enrolled
0.50
Credit / Non-Credit Basis

Class Nbr   Section Component   Days & Times    Room    Instructor  Start/End Date
3148
081
LEC

TBA
Gregory Andres
01/04/2016 - 04/04/2016
Exam Schedule
Materials

Printer Friendly Page
    My Academics                Course Selection (Undergrad Only)               Enroll              Go Pass      
    My Class Schedule               Add             Drop                Swap                Component Swap              Appointments                Search For Classes       
GO!

```

This redirects to /index -> /loginredirect -> /uploadschedule.

Image of sample input source:

http://imgur.com/qs0srg6

My instinct tells me that the source of the issue is the lack of definite times, which throws an error (redirecting them to home). Then the other redirects should be because I'm logged in.

**Comment by nwoodthorpe** [comment]
I'll fix this today. Right now your schedule is parsing as empty, and we don't allow anybody to use the site if they don't have a schedule. We forgot about co op students when designing this, so we'll try to figure out something today.

I've set your schedule to mine for now so you can use the site.

**Comment by nwoodthorpe** [comment]
Co op student's and students without a schedule can now log in and use the site with an empty schedule.
